# CQ-CERT-04: ¿Qué certificados de proyecto tienen un certificado de obra terminada asociado?
# Emparejamiento proyecto→obra terminada vía predecessorCertificate

PREFIX edintcee: <https://edint.es/def/certificado-energetico#>
PREFIX edintceekos-ct: <https://edint.es/kos/EnergyCertificateType/>

SELECT ?completedCert ?projectCert
WHERE {
    ?completedCert a edintcee:EnergyCertificate ;
                    edintcee:predecessorCertificate ?projectCert ;
                    edintcee:certificateType edintceekos-ct:CompletedWork .
    ?projectCert edintcee:certificateType edintceekos-ct:Project .
}
