# CQ-LABEL-01: ¿Qué etiqueta de eficiencia energética tiene asociada un certificado?

PREFIX edintcee: <https://edint.es/def/certificado-energetico#>

SELECT ?cert ?label ?labelLetter
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasLabel ?label .
    ?label edintcee:labelRatingLetter ?labelLetter .
}
