# CQ-USER-01: ¿Se han entregado las recomendaciones de uso al usuario/arrendatario?

PREFIX edintcee: <https://edint.es/def/certificado-energetico#>

SELECT ?cert ?delivered ?recipient ?deliveryDate
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasUserRecommendations ?userRec .
    ?userRec edintcee:userRecommendationsDelivered ?delivered ;
             edintcee:userRecommendationsRecipient ?recipient .
    OPTIONAL { ?userRec edintcee:userRecommendationsDeliveryDate ?deliveryDate }
}
