# FAC-CERT-04: Un certificado tiene exactamente un tipo de certificado (SKOS concept in CertificateType)

PREFIX edintcee: <https://edint.es/def/certificado-energetico#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX edintceekos-ct: <https://edint.es/kos/EnergyCertificateType/>

SELECT ?cert (COUNT(?type) AS ?typeCount)
WHERE {
    ?cert a edintcee:EnergyCertificate .
    OPTIONAL { ?cert edintcee:certificateType ?type }
}
GROUP BY ?cert
HAVING (COUNT(?type) != 1)
